In [13]:
from collections import OrderedDict
import pandas as pd
from sklearn.datasets import load_iris
import numpy as np

dataset = load_iris()
X = dataset.data
Y = dataset.target
print(X)
print(Y)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [14]:
X1 = np.array(X > X.mean(), dtype='int')
print(X1)

[[1 1 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 1 0 0]
 [1 1 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 1 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 1 0 0]
 [1 1 0 0]
 [1 1 0 0]
 [1 1 0 0]
 [1 1 0 0]
 [1 1 0 0]
 [1 0 0 0]
 [1 1 0 0]
 [1 1 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 1 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 1 0 0]
 [1 1 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 1 0 0]
 [1 1 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 1 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 1 0 0]
 [1 1 0 0]
 [1 0 0 0]
 [1 1 0 0]
 [1 0 0 0]
 [1 1 0 0]
 [1 0 0 0]
 [1 0 1 0]
 [1 0 1 0]
 [1 0 1 0]
 [1 0 1 0]
 [1 0 1 0]
 [1 0 1 0]
 [1 0 1 0]
 [1 0 0 0]
 [1 0 1 0]
 [1 0 1 0]
 [1 0 1 0]
 [1 0 1 0]
 [1 0 1 0]
 [1 0 1 0]
 [1 0 1 0]
 [1 0 1 0]
 [1 0 1 0]
 [1 0 1 0]
 [1 0 1 0]
 [1 0 1 0]
 [1 0 1 0]
 [1 0 1 0]
 [1 0 1 0]
 [1 0 1 0]
 [1 0 1 0]
 [1 0 1 0]
 [1 0 1 0]
 [1 0 1 0]
 [1 0 1 0]
 [1 0 1 0]
 [1 0 1 0]
 [1 0 1 0]
 [1 0 1 0]
 [1 0 1 0]
 [1 0 1 0]
 [1 0 1 0]
 [1 0 1 0]
 [1 0 1 0]
 [1 0 1 0]
 [1 0 1 0]
 [1 0 1 0]

In [16]:
Iris_data1 = OrderedDict({'Sepal Length ': X1[:,0],
             'Sepal Width': X1[:,1],
             'Petal Length': X1[:,2],
             'Petal Width': X1[:,3],
             'Label': Y})

df = pd.DataFrame(Iris_data1)
df

Sepal Length   Sepal Width  Petal Length  Petal Width  Label
0                1            1             0            0      0
1                1            0             0            0      0
2                1            0             0            0      0
3                1            0             0            0      0
4                1            1             0            0      0
5                1            1             0            0      0
6                1            0             0            0      0
7                1            0             0            0      0
8                1            0             0            0      0
9                1            0             0            0      0
10               1            1             0            0      0
11               1            0             0            0      0
12               1            0             0            0      0
13               1            0             0            0      0
14               1            1             0            0      0
15               1            1             0            0      0
16               1            1             0            0      0
17               1            1             0            0      0
18               1            1             0            0      0
19               1            1             0            0      0
20               1            0             0            0      0
21               1            1             0            0      0
22               1            1             0            0      0
23               1            0             0            0      0
24               1            0             0            0      0
25               1            0             0            0      0
26               1            0             0            0      0
27               1            1             0            0      0
28               1            0             0            0      0
29               1            0             0            0      0
..             ...          ...           ...          ...    ...
120              1            0             1            0      2
121              1            0             1            0      2
122              1            0             1            0      2
123              1            0             1            0      2
124              1            0             1            0      2
125              1            0             1            0      2
126              1            0             1            0      2
127              1            0             1            0      2
128              1            0             1            0      2
129              1            0             1            0      2
130              1            0             1            0      2
131              1            1             1            0      2
132              1            0             1            0      2
133              1            0             1            0      2
134              1            0             1            0      2
135              1            0             1            0      2
136              1            0             1            0      2
137              1            0             1            0      2
138              1            0             1            0      2
139              1            0             1            0      2
140              1            0             1            0      2
141              1            0             1            0      2
142              1            0             1            0      2
143              1            0             1            0      2
144              1            0             1            0      2
145              1            0             1            0      2
146              1            0             1            0      2
147              1            0             1            0      2
148              1            0             1

### If  type '0'

In [21]:
index, SW, PL, PW = 0, 0, 0, 0

while Y[index] == 0:
    if X1[index][1] == 1:
        SW += 1
    if X1[index][2] == 1:
        PL += 1
    if X1[index][3] == 1:
        PW += 1
    index +=1
    
print (SW, PL, PW)

22 0 0


### If type '1'

In [22]:
SW, PL, PW = 0, 0, 0

while Y[index] == 1:
    if X1[index][1] == 1:
        SW += 1
    if X1[index][2] == 1:
        PL += 1
    if X1[index][3] == 1:
        PW += 1
    index +=1
    
print (SW, PL, PW)

0 47 0
